name: Auto Assign Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Auto assign issues
        if: github.event_name == 'issues'
        uses: pozil/auto-assign-issue@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Baebu
          numOfAssignee: 1

      - name: Auto assign PRs
        if: github.event_name == 'pull_request'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/auto_assign.yml'
